CREATE TABLE IF NOT EXISTS Keys (
    keyID INTEGER PRIMARY KEY, 
    KeyAES TEXT NOT NULL,
    ownerID INTEGER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ownerID) REFERENCES Users (userID)
);